import { StyleSheet } from 'react-native';
import { Colors, Fonts } from '../themes';

const NavigationLtrStyle = StyleSheet.create({
  MenuIcon: {
    fontSize: Fonts.medium,
    color: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.accentColor,
    width: 25,
    height: 25,
    lineHeight: 25,
    textAlign: 'center',
  },
  MenuItem: {
    color: Colors.black,
    textAlign: 'left',
    fontSize: Fonts.small,
    fontWeight: 'bold',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  HeaderView: {
    backgroundColor: Colors.primaryLight,
    color: Colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  MenuView: {
    flex: 1,
  },
  OrdersSection: {
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  OrderItemMenu: {
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  HeaderSection: {
    color: Colors.black,
    textAlign: 'left',
    fontSize: Fonts.h5,
    fontWeight: '200',
    marginBottom: 5,
  },
  AppVersion: {
    color: Colors.primaryDark,
    backgroundColor: Colors.white,
    textAlign: 'left',
    fontSize: Fonts.tiny,
    fontWeight: '200',
    paddingTop: 5,
    paddingHorizontal: 20,
  },
  UserAvatar: {
    color: Colors.primary,
    textAlign: 'center',
    fontSize: Fonts.h6,
    fontWeight: '800',
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
    marginVertical: 5,
    marginHorizontal: 10,
    paddingVertical: 15,
    paddingHorizontal: 15,
    textTransform: 'uppercase',
  },
  HeaderContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    flex: 1,
    justifyContent: 'flex-start',
    marginTop: 5,
    marginBottom: 10,
  },
  HeaderRow: {
    flexDirection: 'row',
  },
  UserText: {
    color: Colors.darkText,
    fontSize: Fonts.medium,
    textTransform: 'capitalize',
  },
  UserEmail: {
    color: Colors.darkText,
    fontSize: Fonts.small,
    marginTop: 5,
  },
  UserRating: {
    color: Colors.darkText,
    fontSize: Fonts.small,
    marginHorizontal: 2,
  },
  ReviewsText: {
    color: Colors.darkText,
    fontSize: Fonts.small,
  },
  MenuSafeAreaView: {
    backgroundColor: Colors.white,
    flex: 1,
  },
  FooterWrapper: {
    flexDirection: 'row',
    marginHorizontal: 0,
    marginVertical: 0,
    paddingVertical: 20,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: Colors.greyBackground,
  },
  FooterLabel: {
    color: Colors.darkText,
    fontWeight: '200',
    marginHorizontal: 0,
    marginVertical: 0,
    paddingVertical: 0,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  FooterIconView: {
    marginHorizontal: 0,
    marginVertical: 0,
    paddingVertical: 0,
    paddingHorizontal: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  LogoutIcon: {
    fontSize: Fonts.medium,
    color: Colors.darkText,
  },
  FlexedYellowView: {
    flex: 1,
    backgroundColor: Colors.primary,
  },
  RatingWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 5,
  },
  RatingText: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default NavigationLtrStyle;
